"""Domain models and exceptions for ChartQA Multimodal Assistant."""

from src.models.chart import (
    ChartExtraction,
    ChartImage,
    ClassificationResult,
    ExtractedDataPoint,
    PipelineResult,
    RAGRetrievalResult,
    ReasoningOutput,
)
from src.models.exceptions import (
    ChartQAError,
    ChartValidationError,
    DataEngineeringError,
    DataFileNotFoundError,
    DataPreprocessingError,
    DivisionByZeroCalcError,
    EmbeddingGenerationError,
    FeatureEngineeringError,
    ForbiddenASTNodeError,
    InvalidExpressionError,
    InvalidVLMOutputError,
    MLModelError,
    ModelNotFoundError,
    PipelineError,
    RAGPipelineError,
    SafeCalculatorError,
    VectorSearchError,
    VLMReasoningError,
)

__all__ = [
    "ChartImage",
    "ChartExtraction",
    "ExtractedDataPoint",
    "ClassificationResult",
    "RAGRetrievalResult",
    "ReasoningOutput",
    "PipelineResult",
    "ChartQAError",
    "SafeCalculatorError",
    "InvalidExpressionError",
    "ForbiddenASTNodeError",
    "DivisionByZeroCalcError",
    "DataEngineeringError",
    "DataFileNotFoundError",
    "DataPreprocessingError",
    "ChartValidationError",
    "FeatureEngineeringError",
    "MLModelError",
    "ModelNotFoundError",
    "EmbeddingGenerationError",
    "RAGPipelineError",
    "VectorSearchError",
    "VLMReasoningError",
    "InvalidVLMOutputError",
    "PipelineError",
]
