"""GeminiQuotaManager tracking API call counts, estimated tokens, errors, latencies, cache hits/misses, and financial cost savings."""

import logging
import time
from typing import Any
from pydantic import BaseModel, Field

logger = logging.getLogger("GeminiQuotaManager")


class GeminiMetricsReport(BaseModel):
    """SRE & Quota report model for Gemini API consumption."""
    total_calls: int = Field(default=0, description="Total API calls made to Gemini")
    cache_hits: int = Field(default=0, description="Total cache hits (avoided Gemini calls)")
    cache_misses: int = Field(default=0, description="Total cache misses (actual Gemini calls)")
    avoided_calls: int = Field(default=0, description="Calls avoided by AST/Pandas/FAISS local routing or cache")
    estimated_input_tokens: int = Field(default=0, description="Estimated input tokens sent to Gemini")
    estimated_output_tokens: int = Field(default=0, description="Estimated output tokens generated by Gemini")
    total_tokens: int = Field(default=0, description="Total estimated tokens consumed")
    total_errors: int = Field(default=0, description="Total API errors encountered")
    total_retries: int = Field(default=0, description="Total automatic retry attempts")
    avg_latency_sec: float = Field(default=0.0, description="Average API latency in seconds")
    max_latency_sec: float = Field(default=0.0, description="Maximum API latency in seconds")
    estimated_cost_saved_usd: float = Field(default=0.0, description="Estimated financial savings in USD from avoided calls")


class GeminiQuotaManager:
    """Enterprise quota and performance metrics manager for Gemini API calls."""

    # Cost estimates: $0.00005 per 1k input tokens, $0.00015 per 1k output tokens, ~$0.002 per VLM vision extraction call
    ESTIMATED_CALL_COST_USD = 0.002

    def __init__(self) -> None:
        self.total_calls = 0
        self.cache_hits = 0
        self.cache_misses = 0
        self.avoided_calls = 0
        self.estimated_input_tokens = 0
        self.estimated_output_tokens = 0
        self.total_errors = 0
        self.total_retries = 0
        self.latencies: list[float] = []

    def record_call(self, input_tokens: int = 500, output_tokens: int = 300, latency_sec: float = 0.4) -> None:
        """Records a successful Gemini API call."""
        self.total_calls += 1
        self.cache_misses += 1
        self.estimated_input_tokens += input_tokens
        self.estimated_output_tokens += output_tokens
        self.latencies.append(latency_sec)
        logger.info(f"GeminiQuotaManager: Recorded API call. Total calls: {self.total_calls}, Total tokens: {self.get_report().total_tokens}")

    def record_cache_hit(self) -> None:
        """Records a cache hit where a Gemini API call was avoided."""
        self.cache_hits += 1
        self.avoided_calls += 1

    def record_local_routing(self) -> None:
        """Records a call avoided by AST/Pandas/FAISS local routing."""
        self.avoided_calls += 1

    def record_error(self) -> None:
        """Records an API error."""
        self.total_errors += 1

    def record_retry(self) -> None:
        """Records an automatic retry attempt."""
        self.total_retries += 1

    def get_report(self) -> GeminiMetricsReport:
        """Returns structured GeminiMetricsReport."""
        tot_tok = self.estimated_input_tokens + self.estimated_output_tokens
        avg_lat = sum(self.latencies) / len(self.latencies) if self.latencies else 0.0
        max_lat = max(self.latencies) if self.latencies else 0.0
        cost_saved = round(self.avoided_calls * self.ESTIMATED_CALL_COST_USD, 4)

        return GeminiMetricsReport(
            total_calls=self.total_calls,
            cache_hits=self.cache_hits,
            cache_misses=self.cache_misses,
            avoided_calls=self.avoided_calls,
            estimated_input_tokens=self.estimated_input_tokens,
            estimated_output_tokens=self.estimated_output_tokens,
            total_tokens=tot_tok,
            total_errors=self.total_errors,
            total_retries=self.total_retries,
            avg_latency_sec=round(avg_lat, 3),
            max_latency_sec=round(max_lat, 3),
            estimated_cost_saved_usd=cost_saved,
        )
